language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t clayton76/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true clayton76/docker-react npm run test